# ==============================================================================
# config.build.yml
# ------------------------------------------------------------------------------
#
# Build-specific values. Hugo supports multiple config files with the
# following syntax:
#
# hugo --config=base.toml,child1.toml,child2.toml
#
# If you are using the Quire commands, this will happen automatically.
#
# Currently these values are set to support deploying to GitHub pages.
# If you are deploying to GH pages, set the baseURL in this file to
# whatever your GH Pages URL will be (username.github.io/project-name, for
# example) and make sure canonifyURLs is set to true. You will also need
# to check the `public/` folder (or whatever you are using for output)
# into version control. Then you can run the deploy script at bin/deploy.sh
# to push files to Github.

baseURL: "http://gettypubs.github.io/quire-demo/"
canonifyURLs: true
