baseURL: 'http://localhost:8080'

title: Quire Starter
languageCode: en-us
theme: default
publishDir: site

footnoteReturnLinkContents: '↩'
GoogleAnalytics: ''

pluralizeListTitles: true
disableKinds:
  - home
  - section
  - taxonomy
  - term

params:
  citationPageLocationDivider: ', '
  citationPopupStyle: text # text | icon
  contributorByline: name-title # name | name-title | false
  entryPageObjectLinkText: View in Collection
  entryPageSideBySideLayout: false
  figureModal: true
  figureModalIcons: true
  figureZoom: true
  imageDir: '/_assets/images'
  licenseIcons: true
  menuType: full
  nextPageButtonText: Next
  pageContributorDivider: ' — '
  pageLabelDivider: '. '
  prevPageButtonText: Back
  searchEnabled: true
  tocType: full

bibliography:
  displayOnPage: true
  displayShort: true
  heading: Bibliography
