languageCode: en-us
theme: default
publishDir: site

footnoteReturnLinkContents: '↩'
GoogleAnalytics: ''

pluralizeListTitles: true
disableKinds:
  - home
  - section
  - taxonomy
  - term

params:
  citationPageLocationDivider: ', '
  citationPopupStyle: text # text | icon
  contributorByline: name-title # name | name-title | false
  entryPageObjectLinkText: View in Collection
  entryPageSideBySideLayout: false
  figureModal: true
  figureModalIcons: true
  figureZoom: true
  imageDir: '/_assets/images'
  licenseIcons: true
  menuType: full
  nextPageButtonText: Next
  pageContributorDivider: ' — '
  pageLabelDivider: '. '
  prevPageButtonText: Back
  searchEnabled: true
  tocType: full

bibliography:
  displayOnPage: true
  displayShort: true
  heading: Bibliography

epub:
  defaultCoverImage: 'https://user-images.githubusercontent.com/7796401/39769476-29929fe4-52a1-11e8-85ac-ff41505b3d4c.png'
  outputDir: '_epub'
