blank_issues_enabled: false  # default: true
contact_links:
- name: ğŸ’¬ Community Forum 
  url: https://github.com/thegetty/quire/discussions
  about: If you have questions, please post them in our GitHub Discussions forum.
- name: ğŸ“ Contributing Guidelines
  url: https://github.com/thegetty/quire/blob/main/CONTRIBUTING.md 
  about: Please take time to review our CONTRIBUTING.md file. 
- name: ğŸ–¥ï¸ Website 
  url: https://quire.getty.edu
  about: Visit our website to learn more about Quire.


